//here is somte text//
on: workflow_dispatch

name: Aikido Scan Dockerized
jobs:
  aikido-local-scan-repo:
    runs-on: ubuntu-latest
    container:
      image: aikidosecurity/local-scanner:latest
    steps: 
      - uses: actions/checkout@v4 
        with: 
          token: ${{ secrets.GITHUB_TOKEN }} 
          path: javawebapp
      - name: Run scan
        run: aikido-local-scanner scan javawebapp --repositoryname javawebapp --branchname main --apikey AIK_CI_DrG6aROVnhqhFpznN0sldqgYYC2bFr1TjaRVpasaZwx2z0isQnI75SgUk75DfkvS
